### ISSUE TITLE
error when double clicking tray icon  AttributeError: 'NoneType' object has no attribute 'show'

### ISSUE THREAD

**Issue by vaishakhsnair** [Nixellion/NoROG#1]

**Comment by Nixellion** [comment]
Thank you for showing interest in the project!

That is expected, there is no UI other than the tray icon which you can right click to see current selected profiles, an exit button and popups that show up whenever you use hotkey buttons. All configuration is handled through config file at the moment.

As you can see from "Planned features, ToDo" section of the README.md - GUI is planned but it's at the end of the list.
